### ISSUE TITLE
about backlink

### ISSUE THREAD

**Issue by Shake-Jarjane** [anaclumos/extracranial#28]
Does this process-backlinks Python file have to be run manually with each push, or how does it run automatically?

**Comment by anaclumos** [comment]
It has to be run manually.

- My deployment sequence uses `yarn deploy`. I type that and forget about it.
- `yarn deploy`, which will trigger `yarn run build && npx wrangler pages publish ./build --commit-dirty=true --project-name=memex`
- which `yarn run build` has `build": "yarn run heavy-process && docusaurus build`
- which `yarn run heavy-process` has `yarn run wikilinks && yarn run backlinks` inside.

Please look at [package.json](https://github.com/anaclumos/extracranial/blob/main/package.json) for more info.

**Comment by anaclumos** [comment]
CC-ing @stevejkang @junhoyeo for context.

We were previously talking about the limitations of Docusaurus on the insufficient scalability as a Second Brain framework. We wanted to rebuild a similar mdx bundler tool with first-class Wikilink & i18n support.

Maybe it's really time to rebuild Nextra / Docusaurus! Maybe Paracosm?

**Comment by junhoyeo** [comment]
> Maybe it's really time to rebuild Nextra / Docusaurus! Maybe Paracosm?

Why not? Finally it's time! 🚀
